//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design_Pattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Jobdescription { get; set; }
        public string Number { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> HourlyPay { get; set; }
        public Nullable<decimal> Bounes { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public Nullable<decimal> HouseAllowence { get; set; }
        public Nullable<decimal> MedicalAllowence { get; set; }
        public string ComputerDetails { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
